### ISSUE TITLE
Change path for storage of images and thumbnails

### ISSUE THREAD

**Issue by kuzmandi** [multicolor-rgb/Bludit-MonsterGallery#2]
Hello there,

I'm trying Monster Gallery and have noticed that the paths, where all images are stored, are
```
/bl-plugins/monsterGallery/monsterGalleryImages/
/bl-plugins/monsterGallery/monsterGalleryThumb/
```
I would like to change this paths for security and aesthetic reasons. Do you think this would be possible in a further version of the plugin?

**Comment by multicolor-rgb** [comment]
I think i can:) Next week i will update for default data folder. 
If you like my plugins you can buy me coffe:) 

[bit.ly/donate-multicolor-plugins](https://www.paypal.com/donate/?hosted_button_id=TW6PXVCTM5A72)

**Comment by multicolor-rgb** [comment]
https://github.com/multicolor-rgb/Bludit-MonsterGallery/archive/refs/heads/2.5.zip New version for test- with Data stored on bl-content, and migrator from oldest version (move image,thumb,galleries from old -to new folder, replace url for correct too ). Please Feedback:)

**Comment by kuzmandi** [comment]
I just tested it and it works fine. I would prefer to be able to choose the folder name freely (e.g. "bl-content/files", "bl-content/images" or "bl-content/gallery" instead of "bl-content/monsterGallery/monsterGalleryImages") but it works that way.

Once more: Is there a way to have not all images in the same folder but divided them into subfolders?

Thank you!

**Comment by multicolor-rgb** [comment]
I hope next release - now i developing more than one plugin:)  Thanks for your support and suggestion :) This is something big for me!  

Come on on my discord :) You can test new feature, and we can work together:)
https://discord.gg/u8twk4gF
