### ISSUE TITLE
Add new Gallery default options

### ISSUE THREAD

**Issue by kuzmandi** [multicolor-rgb/Bludit-MonsterGallery#3]
Can you please change it so that (definable) default values are used if no values are entered?
Now I have to type in the pre-filled values again so that you can create the gallery.

**Comment by multicolor-rgb** [comment]
Ofc i do:) i drink little coffe, and i hope next week send new version for test. :D

**Comment by DoCheckor** [comment]
very very big coffee it seems ;-)

**Comment by multicolor-rgb** [comment]
I forget about it :D Soon, i promise.
